Fix multiple definitions when compiling an example when the library was built with make
The reason is that the definition was in the in header files (without extern) and the makefile compiles the files one by one,
duplicating the symbols.

/usr/bin/ld: ../../lib/unix/libSLK.a(SLK_input.o):(.bss+0x10): multiple definition of `layer_count'; ../../lib/unix/libSLK.a(SLK_core.o):(.bss+0x10): first defined here
/usr/bin/ld: ../../lib/unix/libSLK.a(SLK_input.o):(.bss+0x8): multiple definition of `layers'; ../../lib/unix/libSLK.a(SLK_core.o):(.bss+0x8): first defined here
/usr/bin/ld: ../../lib/unix/libSLK.a(SLK_input.o):(.bss+0x0): multiple definition of `current_layer'; ../../lib/unix/libSLK.a(SLK_core.o):(.bss+0x0): first defined here
/usr/bin/ld: ../../lib/unix/libSLK.a(SLK_input.o):(.bss+0x14): multiple definition of `dynamic'; ../../lib/unix/libSLK.a(SLK_core.o):(.bss+0x14): first defined here
/usr/bin/ld: ../../lib/unix/libSLK.a(SLK_layer.o):(.bss+0x10): multiple definition of `layer_count'; ../../lib/unix/libSLK.a(SLK_core.o):(.bss+0x10): first defined here
/usr/bin/ld: ../../lib/unix/libSLK.a(SLK_layer.o):(.bss+0x8): multiple definition of `layers'; ../../lib/unix/libSLK.a(SLK_core.o):(.bss+0x8): first defined here
/usr/bin/ld: ../../lib/unix/libSLK.a(SLK_layer.o):(.bss+0x0): multiple definition of `current_layer'; ../../lib/unix/libSLK.a(SLK_core.o):(.bss+0x0): first defined here
/usr/bin/ld: ../../lib/unix/libSLK.a(SLK_layer.o):(.bss+0x18): multiple definition of `target_pal_default'; ../../lib/unix/libSLK.a(SLK_draw_pal.o):(.bss+0x0): first defined here
/usr/bin/ld: ../../lib/unix/libSLK.a(SLK_layer.o):(.bss+0x20): multiple definition of `target_pal'; ../../lib/unix/libSLK.a(SLK_draw_pal.o):(.bss+0x8): first defined here
/usr/bin/ld: ../../lib/unix/libSLK.a(SLK_layer.o):(.bss+0x28): multiple definition of `target_rgb_default'; ../../lib/unix/libSLK.a(SLK_draw_rgb.o):(.bss+0x0): first defined here
/usr/bin/ld: ../../lib/unix/libSLK.a(SLK_layer.o):(.bss+0x30): multiple definition of `target_rgb'; ../../lib/unix/libSLK.a(SLK_draw_rgb.o):(.bss+0x8): first defined here
/usr/bin/ld: ../../lib/unix/libSLK.a(SLK_layer.o):(.bss+0x14): multiple definition of `dynamic'; ../../lib/unix/libSLK.a(SLK_core.o):(.bss+0x14): first defined here
/usr/bin/ld: ../../lib/unix/libSLK.a(backend_sdl2_gl.o):(.bss+0x14): multiple definition of `dynamic'; ../../lib/unix/libSLK.a(SLK_core.o):(.bss+0x14): first defined here
/usr/bin/ld: ../../lib/unix/libSLK.a(backend_sdl2_gl.o):(.bss+0x10): multiple definition of `layer_count'; ../../lib/unix/libSLK.a(SLK_core.o):(.bss+0x10): first defined here
/usr/bin/ld: ../../lib/unix/libSLK.a(backend_sdl2_gl.o):(.bss+0x8): multiple definition of `layers'; ../../lib/unix/libSLK.a(SLK_core.o):(.bss+0x8): first defined here
/usr/bin/ld: ../../lib/unix/libSLK.a(backend_sdl2_gl.o):(.bss+0x0): multiple definition of `current_layer'; ../../lib/unix/libSLK.a(SLK_core.o):(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status